name: Flutter CI

on:
  push:
    branches:
      - start_project

jobs:
  build:
    steps:
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle
